// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD86EerNPNoLsaVtFv149tfDSHNGUaRetA',
    appId: '1:1001721401197:web:4d8cb4c665fc0ab8139464',
    messagingSenderId: '1001721401197',
    projectId: 'giragiramap',
    authDomain: 'giragiramap.firebaseapp.com',
    storageBucket: 'giragiramap.firebasestorage.app',
    measurementId: 'G-SCDT0W5GWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JVJLuj7h2lse4k1ZeyplbOUfux_UAoE',
    appId: '1:1001721401197:android:3ce6c5f306d9ac9b139464',
    messagingSenderId: '1001721401197',
    projectId: 'giragiramap',
    storageBucket: 'giragiramap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtPoukouG2CWb_QIK8NdRc1qKSHZuv1Q',
    appId: '1:1001721401197:ios:bc8f55fd8679b3f3139464',
    messagingSenderId: '1001721401197',
    projectId: 'giragiramap',
    storageBucket: 'giragiramap.firebasestorage.app',
    iosBundleId: 'com.example.giragiramap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtPoukouG2CWb_QIK8NdRc1qKSHZuv1Q',
    appId: '1:1001721401197:ios:bc8f55fd8679b3f3139464',
    messagingSenderId: '1001721401197',
    projectId: 'giragiramap',
    storageBucket: 'giragiramap.firebasestorage.app',
    iosBundleId: 'com.example.giragiramap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD86EerNPNoLsaVtFv149tfDSHNGUaRetA',
    appId: '1:1001721401197:web:f16cd2b744a38b87139464',
    messagingSenderId: '1001721401197',
    projectId: 'giragiramap',
    authDomain: 'giragiramap.firebaseapp.com',
    storageBucket: 'giragiramap.firebasestorage.app',
    measurementId: 'G-VRXE42T5KV',
  );
}
